server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://teraenergy.iptime.org:13306/mjy?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8  
      username: mjy
      password: mjy2021
    
    