server: 
  port: 8000
  servlet:
      context-path: /
    
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
      
spring: 
  mvc: 
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: 
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://teraenergy.iptime.org:13306/teware?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: teware
    password: 2021

#  datasource: 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://teraenergy.iptime.org:13306/ojh?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
#    username: ojh
#    password: ojh2021
    