server: 
  port: 8000
  servlet:
      context-path: /
      

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


      
spring: 
  mvc: 
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://teraenergy.iptime.org:13306/ojh?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ojh
    password: ojh2021
    